ROLE_SKILLS = {
    "software-engineer": {
        "label": "Software Engineer",
        "required": [
            "python",
            "javascript",
            "typescript",
            "react",
            "node",
            "sql",
            "git",
            "api",
            "testing",
            "docker",
        ],
        "advanced": ["system design", "microservices", "aws", "ci/cd", "kubernetes"],
    },
    "data-analyst": {
        "label": "Data Analyst",
        "required": [
            "sql",
            "excel",
            "python",
            "power bi",
            "tableau",
            "statistics",
            "dashboard",
            "data cleaning",
        ],
        "advanced": ["a/b testing", "forecasting", "etl", "dbt", "stakeholder"],
    },
    "data-scientist": {
        "label": "Data Scientist",
        "required": [
            "python",
            "sql",
            "machine learning",
            "statistics",
            "pandas",
            "numpy",
            "scikit-learn",
            "model",
        ],
        "advanced": ["deep learning", "nlp", "mlops", "feature engineering", "experiment"],
    },
    "ai-engineer": {
        "label": "AI Engineer",
        "required": [
            "python",
            "machine learning",
            "deep learning",
            "nlp",
            "tensorflow",
            "pytorch",
            "llm",
            "api",
            "vector database",
            "deployment",
        ],
        "advanced": ["rag", "langchain", "transformers", "mlops", "model evaluation", "fine tuning"],
    },
    "frontend-developer": {
        "label": "Frontend Developer",
        "required": [
            "html",
            "css",
            "javascript",
            "typescript",
            "react",
            "accessibility",
            "responsive",
            "testing",
        ],
        "advanced": ["next.js", "performance", "design system", "redux", "tailwind"],
    },
    "backend-developer": {
        "label": "Backend Developer",
        "required": [
            "python",
            "java",
            "node",
            "sql",
            "api",
            "database",
            "testing",
            "docker",
        ],
        "advanced": ["microservices", "redis", "kafka", "aws", "kubernetes"],
    },
    "product-manager": {
        "label": "Product Manager",
        "required": [
            "roadmap",
            "user research",
            "analytics",
            "prioritization",
            "stakeholder",
            "agile",
            "metrics",
        ],
        "advanced": ["go-to-market", "experimentation", "pricing", "strategy", "okr"],
    },
    "mechanical-engineer": {
        "label": "Mechanical Engineer",
        "required": ["autocad", "solidworks", "cad", "manufacturing", "mechanical design", "gd&t", "quality control", "maintenance"],
        "advanced": ["ansys", "fea", "lean manufacturing", "six sigma", "cnc", "thermal analysis"],
    },
    "automobile-engineer": {
        "label": "Automobile Engineer",
        "required": ["automotive", "vehicle dynamics", "engine", "ev", "diagnostics", "cad", "manufacturing", "quality control"],
        "advanced": ["catia", "powertrain", "battery management", "adas", "embedded systems", "simulation"],
    },
    "hardware-engineer": {
        "label": "Hardware Engineer",
        "required": ["circuit design", "pcb", "schematics", "embedded systems", "microcontroller", "testing", "debugging", "electronics"],
        "advanced": ["fpga", "verilog", "vhdl", "signal integrity", "iot", "firmware"],
    },
    "graphic-designer": {
        "label": "Graphic Designer",
        "required": ["photoshop", "illustrator", "figma", "typography", "branding", "layout", "color theory", "portfolio"],
        "advanced": ["motion graphics", "after effects", "ui design", "design system", "print design", "art direction"],
    },
    "digital-marketer": {
        "label": "Digital Marketer",
        "required": ["seo", "content marketing", "social media", "google analytics", "campaigns", "email marketing", "copywriting", "analytics"],
        "advanced": ["sem", "ppc", "marketing automation", "conversion rate", "a/b testing", "crm"],
    },
    "finance-analyst": {
        "label": "Finance Analyst",
        "required": ["excel", "financial modeling", "forecasting", "budgeting", "accounting", "valuation", "reporting", "analytics"],
        "advanced": ["power bi", "tableau", "risk analysis", "variance analysis", "portfolio", "erp"],
    },
    "healthcare-professional": {
        "label": "Healthcare Professional",
        "required": ["patient care", "clinical", "diagnosis", "medical records", "communication", "teamwork", "compliance", "safety"],
        "advanced": ["emr", "triage", "case management", "healthcare analytics", "quality improvement", "hipaa"],
    },
    "custom-role": {
        "label": "Custom Role",
        "required": ["communication", "problem solving", "teamwork", "leadership", "quality", "documentation", "customer service"],
        "advanced": ["project management", "analytics", "process improvement", "training", "stakeholder"],
    },
}

GLOBAL_SKILLS = sorted(
    {
        skill
        for role in ROLE_SKILLS.values()
        for group in ("required", "advanced")
        for skill in role[group]
    }
    | {
        "c++",
        "c#",
        "flask",
        "django",
        "fastapi",
        "mongodb",
        "postgresql",
        "firebase",
        "linux",
        "azure",
        "gcp",
        "figma",
        "jira",
        "leadership",
        "communication",
        "problem solving",
        "ai",
        "ml",
        "tensorflow",
        "pytorch",
        "keras",
        "opencv",
        "computer vision",
        "rag",
        "llm",
        "langchain",
        "transformers",
        "vector database",
        "pinecone",
        "chroma",
        "model evaluation",
        "fine tuning",
        "deployment",
        "rest api",
        "rest apis",
        "autocad",
        "solidworks",
        "cad",
        "catia",
        "ansys",
        "fea",
        "gd&t",
        "manufacturing",
        "mechanical design",
        "quality control",
        "maintenance",
        "lean manufacturing",
        "six sigma",
        "cnc",
        "thermal analysis",
        "automotive",
        "vehicle dynamics",
        "engine",
        "ev",
        "diagnostics",
        "powertrain",
        "battery management",
        "adas",
        "circuit design",
        "pcb",
        "schematics",
        "microcontroller",
        "electronics",
        "fpga",
        "verilog",
        "vhdl",
        "signal integrity",
        "iot",
        "firmware",
        "photoshop",
        "illustrator",
        "typography",
        "branding",
        "layout",
        "color theory",
        "portfolio",
        "motion graphics",
        "after effects",
        "ui design",
        "print design",
        "art direction",
        "seo",
        "content marketing",
        "social media",
        "google analytics",
        "campaigns",
        "email marketing",
        "copywriting",
        "sem",
        "ppc",
        "marketing automation",
        "conversion rate",
        "crm",
        "financial modeling",
        "budgeting",
        "accounting",
        "valuation",
        "reporting",
        "risk analysis",
        "variance analysis",
        "erp",
        "patient care",
        "clinical",
        "diagnosis",
        "medical records",
        "compliance",
        "safety",
        "emr",
        "triage",
        "case management",
        "healthcare analytics",
        "quality improvement",
        "hipaa",
        "teamwork",
        "documentation",
        "customer service",
        "project management",
        "process improvement",
        "training",
        "quality",
    }
)

CONTEXT_PATTERNS = {
    "machine learning": [
        r"\bml\b",
        r"machine learning",
        r"predictive model",
        r"classification model",
        r"regression model",
    ],
    "deep learning": [r"deep learning", r"neural network", r"cnn\b", r"rnn\b", r"lstm\b"],
    "nlp": [r"\bnlp\b", r"natural language", r"text classification", r"sentiment analysis", r"chatbot"],
    "computer vision": [r"computer vision", r"image classification", r"object detection", r"opencv"],
    "api": [r"\bapi\b", r"rest api", r"rest apis", r"endpoint", r"backend service"],
    "deployment": [r"deployed", r"deployment", r"hosted", r"production", r"containerized"],
    "model evaluation": [r"accuracy", r"precision", r"recall", r"f1 score", r"auc"],
    "rag": [r"\brag\b", r"retrieval augmented", r"vector search"],
    "llm": [r"\bllm\b", r"large language model", r"openai", r"gemini"],
    "mechanical design": [r"mechanical design", r"machine design", r"product design"],
    "quality control": [r"quality control", r"\bqc\b", r"inspection", r"root cause"],
    "manufacturing": [r"manufacturing", r"production", r"assembly line", r"plant operations"],
    "automotive": [r"automotive", r"automobile", r"vehicle", r"cars?"],
    "electronics": [r"electronics", r"electronic circuits?", r"hardware testing"],
    "pcb": [r"\bpcb\b", r"printed circuit"],
    "branding": [r"brand identity", r"branding", r"visual identity"],
    "seo": [r"\bseo\b", r"search engine optimization"],
    "analytics": [r"analytics", r"dashboard", r"reporting", r"kpi"],
    "patient care": [r"patient care", r"clinical care", r"bedside care"],
}

ACTION_VERBS = [
    "built",
    "created",
    "designed",
    "developed",
    "implemented",
    "improved",
    "increased",
    "reduced",
    "optimized",
    "automated",
    "launched",
    "led",
    "managed",
    "analyzed",
    "delivered",
    "coordinated",
    "fabricated",
    "inspected",
    "diagnosed",
    "repaired",
    "illustrated",
    "branded",
    "marketed",
    "audited",
    "treated",
    "documented",
]

SECTION_KEYWORDS = {
    "summary": ["summary", "profile", "objective"],
    "experience": ["experience", "work history", "employment", "internship"],
    "projects": ["projects", "portfolio"],
    "skills": ["skills", "technical skills", "technologies"],
    "education": ["education", "academic"],
    "certifications": ["certifications", "certificates", "courses"],
    "achievements": ["achievements", "awards", "honors"],
}
