ROLE_SKILLS = {
    "software-engineer": {
        "label": "Software Engineer",
        "required": [
            "python",
            "javascript",
            "typescript",
            "react",
            "node",
            "sql",
            "git",
            "api",
            "testing",
            "docker",
        ],
        "advanced": ["system design", "microservices", "aws", "ci/cd", "kubernetes"],
    },
    "data-analyst": {
        "label": "Data Analyst",
        "required": [
            "sql",
            "excel",
            "python",
            "power bi",
            "tableau",
            "statistics",
            "dashboard",
            "data cleaning",
        ],
        "advanced": ["a/b testing", "forecasting", "etl", "dbt", "stakeholder"],
    },
    "data-scientist": {
        "label": "Data Scientist",
        "required": [
            "python",
            "sql",
            "machine learning",
            "statistics",
            "pandas",
            "numpy",
            "scikit-learn",
            "model",
        ],
        "advanced": ["deep learning", "nlp", "mlops", "feature engineering", "experiment"],
    },
    "ai-engineer": {
        "label": "AI Engineer",
        "required": [
            "python",
            "machine learning",
            "deep learning",
            "nlp",
            "tensorflow",
            "pytorch",
            "llm",
            "api",
            "vector database",
            "deployment",
        ],
        "advanced": ["rag", "langchain", "transformers", "mlops", "model evaluation", "fine tuning"],
    },
    "frontend-developer": {
        "label": "Frontend Developer",
        "required": [
            "html",
            "css",
            "javascript",
            "typescript",
            "react",
            "accessibility",
            "responsive",
            "testing",
        ],
        "advanced": ["next.js", "performance", "design system", "redux", "tailwind"],
    },
    "backend-developer": {
        "label": "Backend Developer",
        "required": [
            "python",
            "java",
            "node",
            "sql",
            "api",
            "database",
            "testing",
            "docker",
        ],
        "advanced": ["microservices", "redis", "kafka", "aws", "kubernetes"],
    },
    "product-manager": {
        "label": "Product Manager",
        "required": [
            "roadmap",
            "user research",
            "analytics",
            "prioritization",
            "stakeholder",
            "agile",
            "metrics",
        ],
        "advanced": ["go-to-market", "experimentation", "pricing", "strategy", "okr"],
    },
}

GLOBAL_SKILLS = sorted(
    {
        skill
        for role in ROLE_SKILLS.values()
        for group in ("required", "advanced")
        for skill in role[group]
    }
    | {
        "c++",
        "c#",
        "flask",
        "django",
        "fastapi",
        "mongodb",
        "postgresql",
        "firebase",
        "linux",
        "azure",
        "gcp",
        "figma",
        "jira",
        "leadership",
        "communication",
        "problem solving",
        "ai",
        "ml",
        "tensorflow",
        "pytorch",
        "keras",
        "opencv",
        "computer vision",
        "rag",
        "llm",
        "langchain",
        "transformers",
        "vector database",
        "pinecone",
        "chroma",
        "model evaluation",
        "fine tuning",
        "deployment",
        "rest api",
        "rest apis",
    }
)

CONTEXT_PATTERNS = {
    "machine learning": [
        r"\bml\b",
        r"machine learning",
        r"predictive model",
        r"classification model",
        r"regression model",
    ],
    "deep learning": [r"deep learning", r"neural network", r"cnn\b", r"rnn\b", r"lstm\b"],
    "nlp": [r"\bnlp\b", r"natural language", r"text classification", r"sentiment analysis", r"chatbot"],
    "computer vision": [r"computer vision", r"image classification", r"object detection", r"opencv"],
    "api": [r"\bapi\b", r"rest api", r"rest apis", r"endpoint", r"backend service"],
    "deployment": [r"deployed", r"deployment", r"hosted", r"production", r"containerized"],
    "model evaluation": [r"accuracy", r"precision", r"recall", r"f1 score", r"auc"],
    "rag": [r"\brag\b", r"retrieval augmented", r"vector search"],
    "llm": [r"\bllm\b", r"large language model", r"openai", r"gemini"],
}

ACTION_VERBS = [
    "built",
    "created",
    "designed",
    "developed",
    "implemented",
    "improved",
    "increased",
    "reduced",
    "optimized",
    "automated",
    "launched",
    "led",
    "managed",
    "analyzed",
    "delivered",
]

SECTION_KEYWORDS = {
    "summary": ["summary", "profile", "objective"],
    "experience": ["experience", "work history", "employment", "internship"],
    "projects": ["projects", "portfolio"],
    "skills": ["skills", "technical skills", "technologies"],
    "education": ["education", "academic"],
    "certifications": ["certifications", "certificates", "courses"],
    "achievements": ["achievements", "awards", "honors"],
}
